PP-5054 Added library for Java 11
- Container starts with following warnings but works fine and passes end to end tests
     java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
- Added dependency missing for Jersey library for above warning